module.exports = {
  apps: [
    {
      name: 'adonis-web-server',
      script: 'build/bin/server.js',
      interpreter: 'node',
      instances: 'max',
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      shutdown_with_message: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './tmp/logs/pm2-error.log',
      out_file: './tmp/logs/pm2-out.log',
      merge_logs: true,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'adonis-queue-worker',
      script: 'build/ace.js',
      interpreter: 'node',
      args: 'queue:work --concurrency=3',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '200M',
      kill_timeout: 10000,
      shutdown_with_message: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './tmp/logs/pm2-worker-error.log',
      out_file: './tmp/logs/pm2-worker-out.log',
      merge_logs: true,
      env: {
        NODE_ENV: 'production',
      },
    },
  ],
}
