/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Accounts: () => import('#controllers/accounts_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  TelegramWebhook: () => import('#controllers/telegram_webhook_controller'),
  Users: () => import('#controllers/users_controller'),
}
