/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Accounts: () => import('#controllers/accounts_controller'),
  FlexiGrowthOffers: () => import('#controllers/flexi_growth_offers_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Images: () => import('#controllers/images_controller'),
  Products: () => import('#controllers/products_controller'),
  ReturnOtps: () => import('#controllers/return_otps_controller'),
  TelegramWebhook: () => import('#controllers/telegram_webhook_controller'),
  Users: () => import('#controllers/users_controller'),
}
