/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = [
    'autoAcceptOrders',
    'createdAt',
    'email',
    'id',
    'lastLoginAt',
    'password',
    'provider',
    'sessionError',
    'sessionStatus',
    'updatedAt',
    'userId',
  ] as const
  $columns = AccountSchema.$columns
  @column()
  declare autoAcceptOrders: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare provider: string | null
  @column()
  declare sessionError: string | null
  @column()
  declare sessionStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TelegramAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isUpdates', 'updatedAt', 'userId'] as const
  $columns = TelegramAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isUpdates: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: bigint | number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
