/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = [
    'autoAcceptOrders',
    'createdAt',
    'email',
    'id',
    'lastLoginAt',
    'password',
    'provider',
    'sessionError',
    'sessionStatus',
    'updatedAt',
    'userId',
  ] as const
  $columns = AccountSchema.$columns
  @column()
  declare autoAcceptOrders: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare provider: string | null
  @column()
  declare sessionError: string | null
  @column()
  declare sessionStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AdAccountConfigSchema extends BaseModel {
  static $columns = [
    'accountId',
    'apiUrl',
    'createdAt',
    'dynamicFields',
    'id',
    'payload',
    'updatedAt',
  ] as const
  $columns = AdAccountConfigSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare apiUrl: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dynamicFields: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DashboardActivitySchema extends BaseModel {
  static $columns = [
    'action',
    'createdAt',
    'detail',
    'id',
    'read',
    'time',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = DashboardActivitySchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare detail: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare read: boolean
  @column.dateTime()
  declare time: DateTime
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MeeshoLabelDocumentSchema extends BaseModel {
  static $columns = [
    'accountId',
    'awb',
    'color',
    'createdAt',
    'errorCode',
    'errorMessage',
    'id',
    'jobAccountId',
    'jobId',
    'orderId',
    'processedAt',
    'processedPageNumber',
    'processedPdfS3Key',
    'quantity',
    'rawPdfS3Key',
    'size',
    'sku',
    'sourcePageNumber',
    'status',
    'subOrderId',
    'updatedAt',
  ] as const
  $columns = MeeshoLabelDocumentSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare awb: string | null
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jobAccountId: number
  @column()
  declare jobId: string
  @column()
  declare orderId: string | null
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare processedPageNumber: number | null
  @column()
  declare processedPdfS3Key: string | null
  @column()
  declare quantity: number | null
  @column()
  declare rawPdfS3Key: string | null
  @column()
  declare size: string | null
  @column()
  declare sku: string | null
  @column()
  declare sourcePageNumber: number
  @column()
  declare status: string
  @column()
  declare subOrderId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MeeshoLabelJobAccountSchema extends BaseModel {
  static $columns = [
    'accountId',
    'attemptCount',
    'completedAt',
    'createdAt',
    'errorCode',
    'errorMessage',
    'id',
    'identifier',
    'jobId',
    'meeshoRequestId',
    'processedPdfS3Key',
    'progressPercent',
    'rawPdfS3Key',
    'requestedAt',
    'status',
    'successfulSuborders',
    'supplierId',
    'supplierName',
    'totalSuborders',
    'updatedAt',
  ] as const
  $columns = MeeshoLabelJobAccountSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare attemptCount: number | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare jobId: string
  @column()
  declare meeshoRequestId: string | null
  @column()
  declare processedPdfS3Key: string | null
  @column()
  declare progressPercent: number | null
  @column()
  declare rawPdfS3Key: string | null
  @column.dateTime()
  declare requestedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare successfulSuborders: number | null
  @column()
  declare supplierId: string | null
  @column()
  declare supplierName: string | null
  @column()
  declare totalSuborders: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MeeshoLabelJobSchema extends BaseModel {
  static $columns = [
    'completedAccounts',
    'completedAt',
    'createdAt',
    'errorCode',
    'errorMessage',
    'failedAccounts',
    'failedLabels',
    'finalPdfS3Key',
    'finalPdfSize',
    'id',
    'processedLabels',
    'startedAt',
    'status',
    'totalAccounts',
    'totalLabels',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = MeeshoLabelJobSchema.$columns
  @column()
  declare completedAccounts: number | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column()
  declare failedAccounts: number | null
  @column()
  declare failedLabels: number | null
  @column()
  declare finalPdfS3Key: string | null
  @column()
  declare finalPdfSize: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare processedLabels: number | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare totalAccounts: number | null
  @column()
  declare totalLabels: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MeeshoLabelScheduleAccountSchema extends BaseModel {
  static $columns = ['accountId', 'id', 'scheduleId'] as const
  $columns = MeeshoLabelScheduleAccountSchema.$columns
  @column()
  declare accountId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare scheduleId: number
}

export class MeeshoLabelScheduleRunSchema extends BaseModel {
  static $columns = [
    'completedAt',
    'createdAt',
    'id',
    'jobId',
    'scheduleId',
    'scheduledFor',
    'startedAt',
    'status',
  ] as const
  $columns = MeeshoLabelScheduleRunSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jobId: string | null
  @column()
  declare scheduleId: number
  @column.dateTime()
  declare scheduledFor: DateTime
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
}

export class MeeshoLabelScheduleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'cronExpression',
    'daysOfWeek',
    'enabled',
    'frequency',
    'id',
    'lastRunAt',
    'name',
    'nextRunAt',
    'runTime',
    'timezone',
    'updatedAt',
    'userId',
  ] as const
  $columns = MeeshoLabelScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cronExpression: string | null
  @column()
  declare daysOfWeek: any | null
  @column()
  declare enabled: boolean
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare runTime: string
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ProductSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'currentStock',
    'id',
    'imagePath',
    'isActive',
    'minimumStock',
    'name',
    'note',
    'price',
    'updatedAt',
    'userId',
  ] as const
  $columns = ProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currentStock: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePath: string | null
  @column()
  declare isActive: boolean
  @column()
  declare minimumStock: number
  @column()
  declare name: string
  @column()
  declare note: string | null
  @column()
  declare price: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RefreshTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'updatedAt', 'userId'] as const
  $columns = RefreshTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ShippingPriceSchema extends BaseModel {
  static $columns = [
    'accountId',
    'batchName',
    'createdAt',
    'errorMessage',
    'id',
    'imagePath',
    'isProcessed',
    'meeshoImageUrl',
    'price',
    'subSubCategoryId',
    'updatedAt',
  ] as const
  $columns = ShippingPriceSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare batchName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePath: string
  @column()
  declare isProcessed: boolean
  @column()
  declare meeshoImageUrl: string | null
  @column()
  declare price: number | null
  @column()
  declare subSubCategoryId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StockTransactionSchema extends BaseModel {
  static $columns = [
    'changeAmount',
    'createdAt',
    'id',
    'note',
    'productId',
    'stockAfter',
    'type',
    'userId',
  ] as const
  $columns = StockTransactionSchema.$columns
  @column()
  declare changeAmount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare productId: number
  @column()
  declare stockAfter: number
  @column()
  declare type: string
  @column()
  declare userId: number
}

export class TelegramAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isUpdates', 'updatedAt', 'userId'] as const
  $columns = TelegramAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isUpdates: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: bigint | number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
